import fs from "node:fs";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(root, ".env");

if (fs.existsSync(envPath)) {
  console.log(`Configuration already exists: ${envPath}`);
  process.exit(0);
}

const secret = randomBytes(16).toString("hex");
const content = `# Generated by npm run init
OPENREMOTE_HOST=0.0.0.0
OPENREMOTE_PORT=17880
OPENREMOTE_DB_PATH=./data/openremote.sqlite
OPENREMOTE_PUBLIC_URL=http://localhost:17880
OPENREMOTE_SECURE_COOKIES=false
OPENREMOTE_TRUST_PROXY=true
OPENREMOTE_SESSION_HOURS=12
GUACAMOLE_PUBLIC_URL=http://localhost:17880/guacamole/
GUACAMOLE_JSON_SECRET=${secret}
`;

fs.writeFileSync(envPath, content, { encoding: "utf8", mode: 0o600 });
console.log(`Created ${envPath}`);
console.log("Next: docker compose up --build");
